baseURL = "https://simonlee2.github.io/"
languageCode = "en-us"
title = "Simon Lee"
theme = "hyde"

[params]
  description = "My thoughts and stuff"
  themeColor = "theme-base-08"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/about"

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"